import { defineCollection, z } from "astro:content";

const publications = defineCollection({ type: "content", schema: z.object({ title: z.string(), authors: z.array(z.string()), venue: z.string().optional(), year: z.number(), date: z.coerce.date().optional(), status: z.string().optional(), summary: z.string(), tags: z.array(z.string()).default([]), featured: z.boolean().default(false), paper: z.string().url().optional(), code: z.string().url().optional(), project: z.string().optional(), bibtex: z.string().optional(), doi: z.string().optional() }) });
const projects = defineCollection({ type: "content", schema: z.object({ title: z.string(), status: z.string(), summary: z.string(), tags: z.array(z.string()).default([]), featured: z.boolean().default(false), image: z.string().optional(), collaborators: z.array(z.string()).default([]), paper: z.string().url().optional(), code: z.string().url().optional(), external: z.string().url().optional(), relatedPublications: z.array(z.string()).default([]) }) });
const updates = defineCollection({ type: "content", schema: z.object({ date: z.coerce.date(), category: z.enum(["research", "publication", "teaching", "technical", "academic", "career", "life", "general"]), title: z.string(), description: z.string().optional(), featured: z.boolean().default(false), image: z.string().optional(), externalLink: z.string().url().optional(), internalLink: z.string().optional() }) });
const notes = defineCollection({ type: "content", schema: z.object({ title: z.string(), date: z.coerce.date(), description: z.string(), category: z.enum(["Technical", "Research", "Academic", "Tutorial", "Life"]), tags: z.array(z.string()).default([]), featuredImage: z.string().optional(), draft: z.boolean().default(false) }) });
const experience = defineCollection({ type: "data", schema: z.object({ role: z.string(), organization: z.string(), location: z.string().optional(), startDate: z.string(), endDate: z.string().optional(), description: z.string().optional(), tags: z.array(z.string()).default([]) }) });
const education = defineCollection({ type: "data", schema: z.object({ degree: z.string(), field: z.string(), institution: z.string(), startDate: z.string().optional(), endDate: z.string().optional(), status: z.string(), description: z.string().optional() }) });
const teaching = defineCollection({ type: "data", schema: z.object({ courseCode: z.string(), courseName: z.string().optional(), institution: z.string(), role: z.string(), term: z.string().optional(), year: z.number().optional(), description: z.string().optional() }) });
const certifications = defineCollection({ type: "data", schema: z.object({ title: z.string(), issuer: z.string(), issued: z.string(), credentialId: z.string().optional(), credential: z.string().url().optional(), tags: z.array(z.string()).default([]) }) });
export const collections = { publications, projects, updates, notes, experience, education, teaching, certifications };
